### ISSUE TITLE
Review the usage of `.Result`

### ISSUE THREAD

**Issue by kblok** [hlaueriksson/puppeteer-sharp-contrib#1]
Methods like [Id](https://github.com/hlaueriksson/puppeteer-sharp-contrib/blob/master/src/PuppeteerSharp.Contrib.Extensions/ElementHandleAttributeExtensions.cs#L30) can be extremely dangerous. The `Result` method is used in Parallel Libraries, and it should never be used in async code. `Result` will deadlock the code in many circumstances, and I think in that code it would even fail if the task was not resolved yet.

There are many posts about this, here's one https://montemagno.com/c-sharp-developers-stop-calling-dot-result/

Great job with this library :)

**Comment by hlaueriksson** [comment]
Thanks for the review!

Your summary in http://www.hardkoded.com/blog/going-deeper-async is great.
As I understand it, `GetAwaiter().GetResult()` on a task is OK.
The `Result()` method in [Id](https://github.com/hlaueriksson/puppeteer-sharp-contrib/blob/master/src/PuppeteerSharp.Contrib.Extensions/ElementHandleAttributeExtensions.cs#L30) is implemented like this:

```
internal static T Result<T>(this Task<T> task)
{
    return task.GetAwaiter().GetResult();
}
```

Do you think this code is unsafe?

**Comment by kblok** [comment]
So `.Result` will fail for sure. `.GetAwaiter().GetResult();` might work but depending on the scenario (the SynchronizationContext being used).

Rule of thumb **async all the way**. There is no reason these days not to use async/await across the board. A console app supports that, xunit supports that. IMHO I wouldn't support psudo-sync tasks. It will give you headaches, you might get deadlocked.

**Comment by hlaueriksson** [comment]
I'm using `.GetAwaiter().GetResult()` in conjunction with `ConfigureAwait(false)`.

I agree with using async all the way. The [IdAsync](https://github.com/hlaueriksson/puppeteer-sharp-contrib/blob/master/src/PuppeteerSharp.Contrib.Extensions/ElementHandleAttributeExtensions.cs#L18) can achieve than.

The non async methods provide convenience and I think it's valuable when writing non production code.

Consider an acceptance test like this:

```
[Fact]
public async Task Foo()
{
    await Page.SetContentAsync("<html><body><input id='foo' /></body></html>");

    if (Page.QuerySelectorAsync("input").Id() == "foo")
    {
        // do something
    }

    if (await (await Page.QuerySelectorAsync("input")).IdAsync() == "foo")
    {
        // do something
    }
}
```

**Comment by hlaueriksson** [comment]
Hi @kblok 

It's about time to resolve this issue.

A few days ago I released a new version and the _sync over async_ methods has been moved to the new unsafe packages:

* [PuppeteerSharp.Contrib.Extensions.Unsafe](https://github.com/hlaueriksson/puppeteer-sharp-contrib/blob/master/PuppeteerSharp.Contrib.Extensions.Unsafe.md)
* [PuppeteerSharp.Contrib.Should.Unsafe](https://github.com/hlaueriksson/puppeteer-sharp-contrib/blob/master/PuppeteerSharp.Contrib.Should.Unsafe.md)

So, the original packages are all async from now on and should be safe in terms of deadlocks.

This is a breaking change, so I bumped the version to `2.0.0` 💥

**Comment by kblok** [comment]
That's awesome. I think we are going to have a few new versions soon ;)
