### ISSUE TITLE
Add stealth plugin 

### ISSUE THREAD

**Issue by games** [hlaueriksson/puppeteer-sharp-contrib#10]
Hi there, just want to ask if you guys have plan to add support like this?

https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth

thanks

**Comment by hlaueriksson** [comment]
Hi @games 

I just stumbled upon a project from @Overmiind that does that; https://github.com/Overmiind/Puppeteer-sharp-extra

**Comment by games** [comment]
@hlaueriksson oh awesome, thanks
