### ISSUE TITLE
Can this be used with Docker and .Net 6 on linux

### ISSUE THREAD

**Issue by runxc1** [hlaueriksson/puppeteer-sharp-contrib#15]
Curious if this can work in a Linux Container running .Net 6

**Comment by hlaueriksson** [comment]
I haven't tried that, but I'm sure @kblok will be able to answer you.
Check out his repo; https://github.com/hardkoded/docker-puppeteer-sharp

**Comment by kblok** [comment]
That docker is still on 2.1 🙈 
PRs are welcome there.

**Comment by hlaueriksson** [comment]
@kblok also has a blog post on that topic; https://www.hardkoded.com/blog/puppeteer-sharp-docker
