### ISSUE TITLE
the chrome process can't dispose when site host in iis and in hostingModel="InProcess"  mode

### ISSUE THREAD

**Issue by xxgg945** [hlaueriksson/puppeteer-sharp-contrib#7]
![image](https://user-images.githubusercontent.com/7288511/83322631-ef781680-a28b-11ea-9f49-d5388b58771c.png)
when site start it create 4 chrome process
when site stop thease process can dispose in  hostingModel="OutOfProcess"
but when i change web.config hostingModel="InProcess" 
thease chrome process can't dispose
why

**Comment by hlaueriksson** [comment]
Hi, I see that you created an issue here; https://github.com/hardkoded/puppeteer-sharp/issues/1493

That is the appropriate repository to get help 👍 
I hope @kblok can answer.
