### ISSUE TITLE
Hi, first thank you for this wonderful framework.

### ISSUE THREAD

**Issue by TheMurxOr** [hlaueriksson/puppeteer-sharp-contrib#8]
To make this a bit more extraordinary, I have this feature request.
In the ElementHandleExtensions class, within JS evaluation of the content regex
```
  @"(element, selector, regex) => {
                    var elements = element.querySelectorAll(selector);
                    return Array.prototype.find.call(elements, function(element) {
                        return RegExp(regex).test(element.textContent);
                    });
                }",``
```
Is it possible to extend the with a flag object RegExp(regex,**flags**), to pass modifiers like case-insensitive into the regex?
Cheers 
Till

**Comment by hlaueriksson** [comment]
Hi, thanks for your feature request! I will include this in the next release 🎏

**Comment by hlaueriksson** [comment]
I now have a PR for this; https://github.com/hlaueriksson/puppeteer-sharp-contrib/pull/9

@TheMurxOr what do you think about that?

**Comment by TheMurxOr** [comment]
cool thx

**Comment by hlaueriksson** [comment]
Version `3.0.0` is now published and flags are included:

- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Extensions/3.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Should/3.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Extensions.Unsafe/3.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Should.Unsafe/3.0.0

**Comment by TheMurxOr** [comment]
Works like a charm
